#############################################################################
# Makefile for building: djon
# Generated by qmake (2.01a) (Qt 4.6.2) on: Wed Aug 4 13:14:09 2010
# Project:  djon.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile djon.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Idata -Iutil -Iview -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lXss -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = data.cpp \
		main.cpp \
		MainWindow.cpp \
		taskdelegate.cpp \
		taskdialog.cpp \
		taskitem.cpp \
		tasklogmodel.cpp \
		tasklogwindow.cpp \
		template.cpp \
		util.cpp \
		data/project.cpp \
		data/task.cpp \
		util/DateTime.cpp \
		util/fileutil.cpp \
		util/stringfunctions.cpp \
		view/TaskModel.cpp \
		view/taskheaderview.cpp \
		idledetector.cpp \
		timetracker.cpp \
		tasklogdelegate.cpp \
		util/dtime.cpp \
		currenttime.cpp \
		util/errorHandle.cpp \
		view/projectwizard.cpp \
		view/projectinfo.cpp \
		view/projectsummary.cpp \
		view/taskcombobox.cpp \
		treecombobox.cpp \
		idletaskwindow.cpp \
		view/exportdialog.cpp \
		data/exportutility.cpp \
		view/dialogsettings.cpp \
		view/projectdialog.cpp moc_MainWindow.cpp \
		moc_taskdialog.cpp \
		moc_tasklogwindow.cpp \
		moc_TaskModel.cpp \
		moc_taskheaderview.cpp \
		moc_idledetector.cpp \
		moc_timetracker.cpp \
		moc_tasklogdelegate.cpp \
		moc_currenttime.cpp \
		moc_projectwizard.cpp \
		moc_projectinfo.cpp \
		moc_projectsummary.cpp \
		moc_taskcombobox.cpp \
		moc_treecombobox.cpp \
		moc_idletaskwindow.cpp \
		moc_exportdialog.cpp \
		moc_dialogsettings.cpp \
		moc_projectdialog.cpp \
		qrc_djon_rs.cpp
OBJECTS       = data.o \
		main.o \
		MainWindow.o \
		taskdelegate.o \
		taskdialog.o \
		taskitem.o \
		tasklogmodel.o \
		tasklogwindow.o \
		template.o \
		util.o \
		project.o \
		task.o \
		DateTime.o \
		fileutil.o \
		stringfunctions.o \
		TaskModel.o \
		taskheaderview.o \
		idledetector.o \
		timetracker.o \
		tasklogdelegate.o \
		dtime.o \
		currenttime.o \
		errorHandle.o \
		projectwizard.o \
		projectinfo.o \
		projectsummary.o \
		taskcombobox.o \
		treecombobox.o \
		idletaskwindow.o \
		exportdialog.o \
		exportutility.o \
		dialogsettings.o \
		projectdialog.o \
		moc_MainWindow.o \
		moc_taskdialog.o \
		moc_tasklogwindow.o \
		moc_TaskModel.o \
		moc_taskheaderview.o \
		moc_idledetector.o \
		moc_timetracker.o \
		moc_tasklogdelegate.o \
		moc_currenttime.o \
		moc_projectwizard.o \
		moc_projectinfo.o \
		moc_projectsummary.o \
		moc_taskcombobox.o \
		moc_treecombobox.o \
		moc_idletaskwindow.o \
		moc_exportdialog.o \
		moc_dialogsettings.o \
		moc_projectdialog.o \
		qrc_djon_rs.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		djon.pro
QMAKE_TARGET  = djon
DESTDIR       = 
TARGET        = djon

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_MainWindow.h ui_taskdialog.h ui_tasklogwindow.h ui_currenttime.h ui_projectwizard.h ui_projectinfo.h ui_projectsummary.h ui_idletaskwindow.h ui_exportdialog.h ui_dialogsettings.h ui_projectdialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: djon.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile djon.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile djon.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/djon1.0.0 || $(MKDIR) .tmp/djon1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/djon1.0.0/ && $(COPY_FILE) --parents config.h data.h globaldefs.h MainWindow.h taskdelegate.h taskdialog.h taskitem.h tasklogmodel.h tasklogwindow.h template.h util.h data/project.h data/task.h util/DateTime.h util/fileutil.h util/stringfunctions.h view/TaskModel.h view/taskheaderview.h idledetector.h timetracker.h tasklogdelegate.h util/dtime.h currenttime.h util/errorHandle.h view/projectwizard.h view/projectinfo.h view/projectsummary.h view/taskcombobox.h treecombobox.h idletaskwindow.h view/exportdialog.h data/exportutility.h view/dialogsettings.h view/projectdialog.h .tmp/djon1.0.0/ && $(COPY_FILE) --parents djon_rs.qrc .tmp/djon1.0.0/ && $(COPY_FILE) --parents data.cpp main.cpp MainWindow.cpp taskdelegate.cpp taskdialog.cpp taskitem.cpp tasklogmodel.cpp tasklogwindow.cpp template.cpp util.cpp data/project.cpp data/task.cpp util/DateTime.cpp util/fileutil.cpp util/stringfunctions.cpp view/TaskModel.cpp view/taskheaderview.cpp idledetector.cpp timetracker.cpp tasklogdelegate.cpp util/dtime.cpp currenttime.cpp util/errorHandle.cpp view/projectwizard.cpp view/projectinfo.cpp view/projectsummary.cpp view/taskcombobox.cpp treecombobox.cpp idletaskwindow.cpp view/exportdialog.cpp data/exportutility.cpp view/dialogsettings.cpp view/projectdialog.cpp .tmp/djon1.0.0/ && $(COPY_FILE) --parents MainWindow.ui taskdialog.ui tasklogwindow.ui currenttime.ui view/projectwizard.ui view/projectinfo.ui view/projectsummary.ui idletaskwindow.ui view/exportdialog.ui view/dialogsettings.ui view/projectdialog.ui .tmp/djon1.0.0/ && (cd `dirname .tmp/djon1.0.0` && $(TAR) djon1.0.0.tar djon1.0.0 && $(COMPRESS) djon1.0.0.tar) && $(MOVE) `dirname .tmp/djon1.0.0`/djon1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/djon1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_MainWindow.cpp moc_taskdialog.cpp moc_tasklogwindow.cpp moc_TaskModel.cpp moc_taskheaderview.cpp moc_idledetector.cpp moc_timetracker.cpp moc_tasklogdelegate.cpp moc_currenttime.cpp moc_projectwizard.cpp moc_projectinfo.cpp moc_projectsummary.cpp moc_taskcombobox.cpp moc_treecombobox.cpp moc_idletaskwindow.cpp moc_exportdialog.cpp moc_dialogsettings.cpp moc_projectdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_MainWindow.cpp moc_taskdialog.cpp moc_tasklogwindow.cpp moc_TaskModel.cpp moc_taskheaderview.cpp moc_idledetector.cpp moc_timetracker.cpp moc_tasklogdelegate.cpp moc_currenttime.cpp moc_projectwizard.cpp moc_projectinfo.cpp moc_projectsummary.cpp moc_taskcombobox.cpp moc_treecombobox.cpp moc_idletaskwindow.cpp moc_exportdialog.cpp moc_dialogsettings.cpp moc_projectdialog.cpp
moc_MainWindow.cpp: ui_MainWindow.h \
		data.h \
		data/project.h \
		data/task.h \
		util.h \
		util/DateTime.h \
		util/dtime.h \
		util/fileutil.h \
		util/stringfunctions.h \
		util/errorHandle.h \
		template.h \
		taskdelegate.h \
		globaldefs.h \
		idledetector.h \
		MainWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) MainWindow.h -o moc_MainWindow.cpp

moc_taskdialog.cpp: data.h \
		data/project.h \
		data/task.h \
		util.h \
		util/DateTime.h \
		util/dtime.h \
		util/fileutil.h \
		util/stringfunctions.h \
		util/errorHandle.h \
		template.h \
		taskdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) taskdialog.h -o moc_taskdialog.cpp

moc_tasklogwindow.cpp: tasklogwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) tasklogwindow.h -o moc_tasklogwindow.cpp

moc_TaskModel.cpp: data.h \
		data/project.h \
		data/task.h \
		util.h \
		util/DateTime.h \
		util/dtime.h \
		util/fileutil.h \
		util/stringfunctions.h \
		util/errorHandle.h \
		template.h \
		taskitem.h \
		view/TaskModel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) view/TaskModel.h -o moc_TaskModel.cpp

moc_taskheaderview.cpp: view/taskheaderview.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) view/taskheaderview.h -o moc_taskheaderview.cpp

moc_idledetector.cpp: idledetector.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) idledetector.h -o moc_idledetector.cpp

moc_timetracker.cpp: util.h \
		util/DateTime.h \
		util/dtime.h \
		util/fileutil.h \
		util/stringfunctions.h \
		util/errorHandle.h \
		timetracker.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) timetracker.h -o moc_timetracker.cpp

moc_tasklogdelegate.cpp: tasklogdelegate.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) tasklogdelegate.h -o moc_tasklogdelegate.cpp

moc_currenttime.cpp: currenttime.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) currenttime.h -o moc_currenttime.cpp

moc_projectwizard.cpp: view/projectwizard.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) view/projectwizard.h -o moc_projectwizard.cpp

moc_projectinfo.cpp: view/projectinfo.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) view/projectinfo.h -o moc_projectinfo.cpp

moc_projectsummary.cpp: view/projectsummary.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) view/projectsummary.h -o moc_projectsummary.cpp

moc_taskcombobox.cpp: view/taskcombobox.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) view/taskcombobox.h -o moc_taskcombobox.cpp

moc_treecombobox.cpp: treecombobox.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) treecombobox.h -o moc_treecombobox.cpp

moc_idletaskwindow.cpp: idletaskwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) idletaskwindow.h -o moc_idletaskwindow.cpp

moc_exportdialog.cpp: util.h \
		util/DateTime.h \
		util/dtime.h \
		util/fileutil.h \
		util/stringfunctions.h \
		util/errorHandle.h \
		view/exportdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) view/exportdialog.h -o moc_exportdialog.cpp

moc_dialogsettings.cpp: view/dialogsettings.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) view/dialogsettings.h -o moc_dialogsettings.cpp

moc_projectdialog.cpp: view/projectdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) view/projectdialog.h -o moc_projectdialog.cpp

compiler_rcc_make_all: qrc_djon_rs.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_djon_rs.cpp
qrc_djon_rs.cpp: djon_rs.qrc \
		img/media-playback-stop.png \
		img/project.png \
		img/delete_big.png \
		img/media-playback-start.png \
		img/djon.png \
		img/media-record.png \
		img/media-playback-pause.png \
		img/accessories-text-editor.png \
		img/insert-object.png
	/usr/bin/rcc -name djon_rs djon_rs.qrc -o qrc_djon_rs.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_MainWindow.h ui_taskdialog.h ui_tasklogwindow.h ui_currenttime.h ui_projectwizard.h ui_projectinfo.h ui_projectsummary.h ui_idletaskwindow.h ui_exportdialog.h ui_dialogsettings.h ui_projectdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_MainWindow.h ui_taskdialog.h ui_tasklogwindow.h ui_currenttime.h ui_projectwizard.h ui_projectinfo.h ui_projectsummary.h ui_idletaskwindow.h ui_exportdialog.h ui_dialogsettings.h ui_projectdialog.h
ui_MainWindow.h: MainWindow.ui
	/usr/bin/uic-qt4 MainWindow.ui -o ui_MainWindow.h

ui_taskdialog.h: taskdialog.ui
	/usr/bin/uic-qt4 taskdialog.ui -o ui_taskdialog.h

ui_tasklogwindow.h: tasklogwindow.ui
	/usr/bin/uic-qt4 tasklogwindow.ui -o ui_tasklogwindow.h

ui_currenttime.h: currenttime.ui
	/usr/bin/uic-qt4 currenttime.ui -o ui_currenttime.h

ui_projectwizard.h: view/projectwizard.ui
	/usr/bin/uic-qt4 view/projectwizard.ui -o ui_projectwizard.h

ui_projectinfo.h: view/projectinfo.ui
	/usr/bin/uic-qt4 view/projectinfo.ui -o ui_projectinfo.h

ui_projectsummary.h: view/projectsummary.ui
	/usr/bin/uic-qt4 view/projectsummary.ui -o ui_projectsummary.h

ui_idletaskwindow.h: idletaskwindow.ui \
		treecombobox.h
	/usr/bin/uic-qt4 idletaskwindow.ui -o ui_idletaskwindow.h

ui_exportdialog.h: view/exportdialog.ui
	/usr/bin/uic-qt4 view/exportdialog.ui -o ui_exportdialog.h

ui_dialogsettings.h: view/dialogsettings.ui
	/usr/bin/uic-qt4 view/dialogsettings.ui -o ui_dialogsettings.h

ui_projectdialog.h: view/projectdialog.ui
	/usr/bin/uic-qt4 view/projectdialog.ui -o ui_projectdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

data.o: data.cpp data.h \
		data/project.h \
		data/task.h \
		util.h \
		util/DateTime.h \
		util/dtime.h \
		util/fileutil.h \
		util/stringfunctions.h \
		util/errorHandle.h \
		template.h \
		config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o data.o data.cpp

main.o: main.cpp MainWindow.h \
		ui_MainWindow.h \
		data.h \
		data/project.h \
		data/task.h \
		util.h \
		util/DateTime.h \
		util/dtime.h \
		util/fileutil.h \
		util/stringfunctions.h \
		util/errorHandle.h \
		template.h \
		taskdelegate.h \
		globaldefs.h \
		idledetector.h \
		view/TaskModel.h \
		taskitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

MainWindow.o: MainWindow.cpp MainWindow.h \
		ui_MainWindow.h \
		data.h \
		data/project.h \
		data/task.h \
		util.h \
		util/DateTime.h \
		util/dtime.h \
		util/fileutil.h \
		util/stringfunctions.h \
		util/errorHandle.h \
		template.h \
		taskdelegate.h \
		globaldefs.h \
		idledetector.h \
		view/TaskModel.h \
		taskitem.h \
		tasklogwindow.h \
		view/taskheaderview.h \
		timetracker.h \
		currenttime.h \
		taskdialog.h \
		view/projectwizard.h \
		idletaskwindow.h \
		view/dialogsettings.h \
		view/exportdialog.h \
		view/projectdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o MainWindow.cpp

taskdelegate.o: taskdelegate.cpp taskdelegate.h \
		globaldefs.h \
		util.h \
		util/DateTime.h \
		util/dtime.h \
		util/fileutil.h \
		util/stringfunctions.h \
		util/errorHandle.h \
		view/TaskModel.h \
		data.h \
		data/project.h \
		data/task.h \
		template.h \
		taskitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o taskdelegate.o taskdelegate.cpp

taskdialog.o: taskdialog.cpp taskdialog.h \
		data.h \
		data/project.h \
		data/task.h \
		util.h \
		util/DateTime.h \
		util/dtime.h \
		util/fileutil.h \
		util/stringfunctions.h \
		util/errorHandle.h \
		template.h \
		ui_taskdialog.h \
		tasklogmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o taskdialog.o taskdialog.cpp

taskitem.o: taskitem.cpp taskitem.h \
		data.h \
		data/project.h \
		data/task.h \
		util.h \
		util/DateTime.h \
		util/dtime.h \
		util/fileutil.h \
		util/stringfunctions.h \
		util/errorHandle.h \
		template.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o taskitem.o taskitem.cpp

tasklogmodel.o: tasklogmodel.cpp tasklogmodel.h \
		data.h \
		data/project.h \
		data/task.h \
		util.h \
		util/DateTime.h \
		util/dtime.h \
		util/fileutil.h \
		util/stringfunctions.h \
		util/errorHandle.h \
		template.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tasklogmodel.o tasklogmodel.cpp

tasklogwindow.o: tasklogwindow.cpp tasklogwindow.h \
		ui_tasklogwindow.h \
		data.h \
		data/project.h \
		data/task.h \
		util.h \
		util/DateTime.h \
		util/dtime.h \
		util/fileutil.h \
		util/stringfunctions.h \
		util/errorHandle.h \
		template.h \
		tasklogmodel.h \
		tasklogdelegate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tasklogwindow.o tasklogwindow.cpp

template.o: template.cpp template.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o template.o template.cpp

util.o: util.cpp util.h \
		util/DateTime.h \
		util/dtime.h \
		util/fileutil.h \
		util/stringfunctions.h \
		util/errorHandle.h \
		config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o util.o util.cpp

project.o: data/project.cpp data/project.h \
		util.h \
		util/DateTime.h \
		util/dtime.h \
		util/fileutil.h \
		util/stringfunctions.h \
		util/errorHandle.h \
		data.h \
		data/task.h \
		template.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o project.o data/project.cpp

task.o: data/task.cpp data/task.h \
		util.h \
		util/DateTime.h \
		util/dtime.h \
		util/fileutil.h \
		util/stringfunctions.h \
		util/errorHandle.h \
		data.h \
		data/project.h \
		template.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o task.o data/task.cpp

DateTime.o: util/DateTime.cpp util/DateTime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DateTime.o util/DateTime.cpp

fileutil.o: util/fileutil.cpp util/fileutil.h \
		util/stringfunctions.h \
		util/errorHandle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fileutil.o util/fileutil.cpp

stringfunctions.o: util/stringfunctions.cpp util/stringfunctions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stringfunctions.o util/stringfunctions.cpp

TaskModel.o: view/TaskModel.cpp view/TaskModel.h \
		data.h \
		data/project.h \
		data/task.h \
		util.h \
		util/DateTime.h \
		util/dtime.h \
		util/fileutil.h \
		util/stringfunctions.h \
		util/errorHandle.h \
		template.h \
		taskitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TaskModel.o view/TaskModel.cpp

taskheaderview.o: view/taskheaderview.cpp view/taskheaderview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o taskheaderview.o view/taskheaderview.cpp

idledetector.o: idledetector.cpp idledetector.h \
		config.h \
		util.h \
		util/DateTime.h \
		util/dtime.h \
		util/fileutil.h \
		util/stringfunctions.h \
		util/errorHandle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o idledetector.o idledetector.cpp

timetracker.o: timetracker.cpp timetracker.h \
		util.h \
		util/DateTime.h \
		util/dtime.h \
		util/fileutil.h \
		util/stringfunctions.h \
		util/errorHandle.h \
		data.h \
		data/project.h \
		data/task.h \
		template.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o timetracker.o timetracker.cpp

tasklogdelegate.o: tasklogdelegate.cpp tasklogdelegate.h \
		data.h \
		data/project.h \
		data/task.h \
		util.h \
		util/DateTime.h \
		util/dtime.h \
		util/fileutil.h \
		util/stringfunctions.h \
		util/errorHandle.h \
		template.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tasklogdelegate.o tasklogdelegate.cpp

dtime.o: util/dtime.cpp util/dtime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dtime.o util/dtime.cpp

currenttime.o: currenttime.cpp currenttime.h \
		ui_currenttime.h \
		view/TaskModel.h \
		data.h \
		data/project.h \
		data/task.h \
		util.h \
		util/DateTime.h \
		util/dtime.h \
		util/fileutil.h \
		util/stringfunctions.h \
		util/errorHandle.h \
		template.h \
		taskitem.h \
		view/taskcombobox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o currenttime.o currenttime.cpp

errorHandle.o: util/errorHandle.cpp util/errorHandle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o errorHandle.o util/errorHandle.cpp

projectwizard.o: view/projectwizard.cpp view/projectwizard.h \
		ui_projectwizard.h \
		data.h \
		data/project.h \
		data/task.h \
		util.h \
		util/DateTime.h \
		util/dtime.h \
		util/fileutil.h \
		util/stringfunctions.h \
		util/errorHandle.h \
		template.h \
		view/projectinfo.h \
		view/projectsummary.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o projectwizard.o view/projectwizard.cpp

projectinfo.o: view/projectinfo.cpp view/projectinfo.h \
		ui_projectinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o projectinfo.o view/projectinfo.cpp

projectsummary.o: view/projectsummary.cpp view/projectsummary.h \
		ui_projectsummary.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o projectsummary.o view/projectsummary.cpp

taskcombobox.o: view/taskcombobox.cpp view/taskcombobox.h \
		data.h \
		data/project.h \
		data/task.h \
		util.h \
		util/DateTime.h \
		util/dtime.h \
		util/fileutil.h \
		util/stringfunctions.h \
		util/errorHandle.h \
		template.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o taskcombobox.o view/taskcombobox.cpp

treecombobox.o: treecombobox.cpp treecombobox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o treecombobox.o treecombobox.cpp

idletaskwindow.o: idletaskwindow.cpp idletaskwindow.h \
		ui_idletaskwindow.h \
		treecombobox.h \
		data.h \
		data/project.h \
		data/task.h \
		util.h \
		util/DateTime.h \
		util/dtime.h \
		util/fileutil.h \
		util/stringfunctions.h \
		util/errorHandle.h \
		template.h \
		view/TaskModel.h \
		taskitem.h \
		timetracker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o idletaskwindow.o idletaskwindow.cpp

exportdialog.o: view/exportdialog.cpp view/exportdialog.h \
		util.h \
		util/DateTime.h \
		util/dtime.h \
		util/fileutil.h \
		util/stringfunctions.h \
		util/errorHandle.h \
		ui_exportdialog.h \
		data/exportutility.h \
		data.h \
		data/project.h \
		data/task.h \
		template.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o exportdialog.o view/exportdialog.cpp

exportutility.o: data/exportutility.cpp data/exportutility.h \
		data.h \
		data/project.h \
		data/task.h \
		util.h \
		util/DateTime.h \
		util/dtime.h \
		util/fileutil.h \
		util/stringfunctions.h \
		util/errorHandle.h \
		template.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o exportutility.o data/exportutility.cpp

dialogsettings.o: view/dialogsettings.cpp view/dialogsettings.h \
		ui_dialogsettings.h \
		util.h \
		util/DateTime.h \
		util/dtime.h \
		util/fileutil.h \
		util/stringfunctions.h \
		util/errorHandle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialogsettings.o view/dialogsettings.cpp

projectdialog.o: view/projectdialog.cpp view/projectdialog.h \
		ui_projectdialog.h \
		data.h \
		data/project.h \
		data/task.h \
		util.h \
		util/DateTime.h \
		util/dtime.h \
		util/fileutil.h \
		util/stringfunctions.h \
		util/errorHandle.h \
		template.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o projectdialog.o view/projectdialog.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

moc_taskdialog.o: moc_taskdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_taskdialog.o moc_taskdialog.cpp

moc_tasklogwindow.o: moc_tasklogwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tasklogwindow.o moc_tasklogwindow.cpp

moc_TaskModel.o: moc_TaskModel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TaskModel.o moc_TaskModel.cpp

moc_taskheaderview.o: moc_taskheaderview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_taskheaderview.o moc_taskheaderview.cpp

moc_idledetector.o: moc_idledetector.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_idledetector.o moc_idledetector.cpp

moc_timetracker.o: moc_timetracker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_timetracker.o moc_timetracker.cpp

moc_tasklogdelegate.o: moc_tasklogdelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tasklogdelegate.o moc_tasklogdelegate.cpp

moc_currenttime.o: moc_currenttime.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_currenttime.o moc_currenttime.cpp

moc_projectwizard.o: moc_projectwizard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_projectwizard.o moc_projectwizard.cpp

moc_projectinfo.o: moc_projectinfo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_projectinfo.o moc_projectinfo.cpp

moc_projectsummary.o: moc_projectsummary.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_projectsummary.o moc_projectsummary.cpp

moc_taskcombobox.o: moc_taskcombobox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_taskcombobox.o moc_taskcombobox.cpp

moc_treecombobox.o: moc_treecombobox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_treecombobox.o moc_treecombobox.cpp

moc_idletaskwindow.o: moc_idletaskwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_idletaskwindow.o moc_idletaskwindow.cpp

moc_exportdialog.o: moc_exportdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_exportdialog.o moc_exportdialog.cpp

moc_dialogsettings.o: moc_dialogsettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialogsettings.o moc_dialogsettings.cpp

moc_projectdialog.o: moc_projectdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_projectdialog.o moc_projectdialog.cpp

qrc_djon_rs.o: qrc_djon_rs.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_djon_rs.o qrc_djon_rs.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

